// EK stands for "Event Key"

export const EK_LINT_FEEDBACK = "EK_LINT_FEEDBACK";
export const EK_GENERATED_CODE_PLAIN = "EK_GENERATED_CODE_PLAIN"
export const EK_IMAGE_ASSET_REPOSITORY_MAP = "EK_IMAGE_ASSET_REPOSITORY_MAP"
export const EK_PREVIEW_SOURCE = "EK_PREVIEW_SOURCE"
export const EK_COPIED = "EK_COPIED";
export const EK_FOCUS_REQUEST = "EK_FOCUS_REQUEST"
export const EK_CREATE_ICON = "EK_CREATE_ICON"