export enum WorkScreen {
  about = "about",
  /** todo: rename to code/preview */
  code = "code",
  /** @deprecated only used for sendig event */
  code_flutter = "code/flutter",
  /** @deprecated only used for sendig event */
  code_react = "code/react",
  component = "component",
  preview = "preview",
  layout = "layout",
  copy = "copy",
  icon = "icon",
  photo = "photo",
  live = "live",
  lint = "lint",
  g11n = "g11n",
  dev = "dev",
  slot = "slot",
  exporter = "exporter",
  tool_home = "tools",
  tool_desing_button_maker = "tool_desing_button_maker",
  tool_code_syntax_highlighter = "tool_code_syntax_highlighter",
  tool_font_replacer = "tool_font_replacer",
  tool_meta_editor = "tool_meta_editor",
  tool_batch_meta_editor = "tool_batch_meta_editor",
  tool_data_mapper = "tool_data_mapper",
  signin = "signin",
  upgrade = "upgrade",
}
