const __query_placeholders = [
  `Try "An astronaut with cowboy hat"`,
  `Try "Abstract geometric 3D shapes"`,
  `Try "Background"`,
  `Try "Futuristic cityscape with flying cars and towering skyscrapers"`,
  `Try "magical forest with towering trees and a gentle stream running through it."`,
  `Try "Cozy cabin with fire and snow"`,
  `Try "Bustling marketplace with stalls and people"`,
  `Try "An enchanted forest filled with fireflies."`,
  `Try "A quaint village nestled in the countryside"`,
  `Try "A breathtaking mountain range at sunrise"`,
  `Try "A mysterious island shrouded in mist"`,
  `Try "A vibrant marketplace in a bustling city"`,
];
export const radmon_query_placeholder = () => {
  const i = Math.floor(Math.random() * __query_placeholders.length);
  return __query_placeholders[i];
};

export const generative_styles = {
  photorealistic: "Photorealistic",
  abstract: "Abstract",
  pixel: "Pixel",
  minimal: "Minimal",
  geometric: "Geometric",
  catoonish: "Catoonish",
  colorful: "Colorful",
  dark: "Dark",
  light: "Light",
  three_dimensional: "3D",
  two_dimensional: "2D",
  pop_art: "Pop Art",
  mosaic: "Mosaic",
  picasso: "Picasso",
  graffiti: "Graffiti",
  fantasy: "Fantasy",
  steampunk: "Steampunk",
  sci_fi: "Sci-Fi",
  cyberpunk: "Cyberpunk",
  glitch: "Glitch",
  surrealism: "Surrealism",
  neon: "Neon",
  collage: "Collage",
  cubism: "Cubism",
  expressionism: "Expressionism",
  fauvism: "Fauvism",
  gothic: "Gothic",
  futurism: "Futurism",
  art_nouveau: "Art Nouveau",
  renaissance: "Renaissance",
  rococo: "Rococo",
  romanticism: "Romanticism",
  symbolism: "Symbolism",
  dada: "Dada",
  modernism: "Modernism",
  post_modernism: "Post-modernism",
  constructivism: "Constructivism",
  suprematism: "Suprematism",
  de_stijl: "De Stijl",
  bauhaus: "Bauhaus",
  minimalism: "Minimalism",
  conceptual: "Conceptual",
  kinetic_art: "Kinetic art",
  op_art: "Op art",
  Trompe_loeil: "Trompe l'œil",
};
