const ascetic = {
  hljs: { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-string': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-variable': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-template-variable': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-symbol': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-bullet': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-section': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-addition': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-attribute': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-link': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-comment': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-quote': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-meta': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-deletion': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-keyword': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-selector-tag': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-name': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-type': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-strong': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
  'hljs-emphasis': { type: 'SOLID', color: { r: 1, g: 1, b: 1 } },
}
export default ascetic
